name: qiscus_chat_sample
description: Qiscus Chat SDK Sample
version: 1.0.3+alpha1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  firebase_messaging: ^6.0.13
  timeago: ^2.0.26
  provider: ^4.1.1
  async:
  fluttertoast: ^3.1.3
  file_picker: ^1.5.1
  freezed_annotation:
  fluro: ^1.6.1
  date_format: ^1.0.8
  cuid: ^0.1.2
  flutter_bloc:
  qiscus_chat_sdk: ^1.0.0+alpha5
  rxdart:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

# usefull for local development
dependency_overrides:
  qiscus_chat_sdk:
    path: ../qiscus-chat-sdk-flutter

dev_dependencies:
  build_runner:
  freezed:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
