name: qiscus_chat_flutter_sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qiscus_chat_sdk: ^2.0.0-beta.7
  firebase_messaging: ^13.0.3
  timeago: ^3.3.0
  provider: ^6.0.3
  file_picker: ^5.2.0+1
  date_format: ^2.0.7
  grouped_list: ^5.1.2
  flutter_downloader: ^1.8.4
  permission_handler: ^10.0.1
  path_provider: ^2.0.11
  firebase_core: ^1.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
